on:
  workflow_dispatch:
    inputs:
      version:
        required: true
  repository_dispatch:
    types:
      - build

jobs:
  docker:
    if: ${{ github.event.client_payload.version || github.event.inputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Check version
        run: |
          echo Preparing version: $VERSION
          if curl -fs https://hub.docker.com/v2/repositories/gera2ld/pocketbase/tags/$VERSION > /dev/null; then
            echo WARNING: Version exists: $VERSION
          fi
          echo VERSION=$VERSION >> $GITHUB_ENV
        env:
          VERSION: ${{ github.event.client_payload.version || github.event.inputs.version }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: gera2ld/pocketbase:latest,gera2ld/pocketbase:${{ env.VERSION }}
          build-args: POCKETBASE_VERSION=${{ env.VERSION }}
